### ISSUE TITLE
French translation is out of date

### ISSUE THREAD

**Issue by Anteater46** [Anteater46/ModTranslations#1]
The French translation is missing Smoked Bread its tooltip.

**Comment by AlasDiablo** [comment]
For the Smoked bread i think is `Pain brioché`, but with the information on the tool-tip is can also be `Pain perdu`, that depend on the context (I love the french language because we can say one thing with a lot of word or formulation). :sweat_smile: 

Personally I would choose `Pain brioché` for the transaltion of `Smoked bread`.

`Perfect with maple butter!` -> `Parfait avec du beurre d'érable !`

Bonne journée. :wink:

**Comment by Anteater46** [comment]
Thanks for doing this :)

Have a good day :D
